version: "3.9"  # optional since v1.27.0
services:
  redis:
    image: "redis:7.0.2"
    env_file:
    - .env
    command: redis-server --requirepass $REDIS_PASSWORD
    networks:
    - backend
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - redis
    environment:
      - "REDIS_URL=redis:6379"
    env_file:
    - .env
    networks:
    - backend

networks:
  backend:
